ci: Only build affected Docker images

diff --git a/.github/workflows/docker_publish_staging.yml b/.github/workflows/docker_publish_staging.yml
--- a/.github/workflows/docker_publish_staging.yml
+++ b/.github/workflows/docker_publish_staging.yml
@@ -1,10 +1,10 @@
-name: Create and publish Docker images
+name: Create and publish Docker images (Staging)
 
 on:
   workflow_dispatch:
   push:
     branches:
-      - main
+      - staging
 
 env:
   GITHUB_SHA: ${{ github.sha }}
@@ -23,13 +23,18 @@ env:
 
 jobs:
   cache-deps:
-    name: Pull request merge - Validate npm cache for main branch
+    name: Validate npm cache for staging branch and get affected apps
     runs-on: ubuntu-latest
+    outputs:
+      affected_apps: ${{ steps.affected-apps.outputs.affected_apps }}
     steps:
-      - name: Checkout [main]
+      - name: Checkout [staging branch]
         uses: actions/checkout@v4
         with:
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
           fetch-depth: 0
+          filter: tree:0
+          ref: staging
 
       - uses: actions/setup-node@v4
         with:
@@ -45,6 +50,41 @@ jobs:
       - name: Install dependencies
         if: steps.use-npm-cache.outputs.cache-hit != 'true'
         run: npm ci
+
+      - name: Find affected SHAs
+        id: affected-shas
+        uses: nrwl/nx-set-shas@v4 # Sets the NX_BASE and NX_HEAD env variables
+        with:
+          main-branch-name: staging # The branch used to find the base SHA
+
+      - name: Check if Python projects are affected
+        id: check-python
+        # Manually check if files under the python directory have changed with git using the SHAs set in the previous step
+        run: |
+          AFFECTED_PYTHON_FILES=$(git diff --name-only ${{ env.NX_BASE }} ${{ env.NX_HEAD }} | grep "^python/" || true)
+          if [ -z "$AFFECTED_PYTHON_FILES" ]; then
+            echo "No Python files affected."
+            echo "python_affected=false" >> $GITHUB_OUTPUT
+          else
+            echo "Python files affected: $AFFECTED_PYTHON_FILES"
+            echo "python_affected=true" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Determine affected apps
+        id: affected-apps
+        run: |
+          AFFECTED_APPS=$(npx nx show projects --affected --with-target build --type app --json --base ${{ env.NX_BASE }} --head ${{ env.NX_HEAD }})
+
+          if [ "${{ steps.check-python.outputs.python_affected }}" == "true" ]; then
+            if [ -z "$AFFECTED_APPS" ]; then
+              AFFECTED_APPS="[\"python\"]"
+            else
+              AFFECTED_APPS=$(echo $AFFECTED_APPS | jq '. + ["python"]')
+            fi
+          fi
+
+          echo "Affected apps: $AFFECTED_APPS"
+          echo "affected_apps=$AFFECTED_APPS" >> $GITHUB_OUTPUT
 
   build-and-push-image:
     needs: cache-deps
@@ -91,6 +131,7 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - name: Build and push Docker image (web)
+        if: contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api')
         uses: docker/build-push-action@v6
         with:
           context: .
@@ -102,7 +143,7 @@ jobs:
           cache-to: type=gha,mode=max
 
       - name: Build and push Docker image (nginx)
-        if: github.repository != 'cds-snc/cra-arc-upd-tbpc'
+        if: github.repository != 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'upd')
         uses: docker/build-push-action@v6
         with:
           context: .
@@ -114,7 +155,7 @@ jobs:
           cache-to: type=gha,mode=max
 
       - name: Build and push Docker image (db-updater)
-        if: github.repository != 'cds-snc/cra-arc-upd-tbpc'
+        if: github.repository != 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'db-updater')
         uses: docker/build-push-action@v6
         with:
           context: .
@@ -126,7 +167,7 @@ jobs:
           cache-to: type=gha,mode=max
 
       - name: Build and push Docker image (data-import)
-        if: github.repository == 'cds-snc/cra-arc-upd-tbpc'
+        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'python')
         uses: docker/build-push-action@v6
         with:
           context: .
@@ -137,7 +178,7 @@ jobs:
           cache-to: type=gha,mode=max
 
       - name: Build and push Docker image (update-db)
-        if: github.repository == 'cds-snc/cra-arc-upd-tbpc'
+        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && (contains(fromJson(needs.cache-deps.outputs.affected_apps), 'update-db-task') || contains(fromJson(needs.cache-deps.outputs.affected_apps), 'python'))
         uses: docker/build-push-action@v6
         with:
           context: .
@@ -148,13 +189,13 @@ jobs:
           cache-to: type=gha,mode=max
 
       - name: Restart ECS
-        if: github.repository == 'cds-snc/cra-arc-upd-tbpc'
+        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api')
         run: |
           aws ecs update-service --cluster cra-upd-dashboard-cluster --service cra-upd-dashboard-app-service --force-new-deployment > /dev/null 2>&1
 
       # Allow this step to fail so we can handle success/failure and report it to slack. By default it waits for 10 minutes
       - name: Wait for ECS Stability
-        if: github.repository == 'cds-snc/cra-arc-upd-tbpc'
+        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api')
         id: ecs_wait
         continue-on-error: true
         run: |
@@ -167,14 +208,14 @@ jobs:
       # todo: add this back in once we have a stable deployment
       # # Slack notification on failed ECS wait
       # - name: Slack Notify Failure
-      #   if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && steps.ecs_wait.outcome == 'failure'
+      #   if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api') && steps.ecs_wait.outcome == 'failure'
       #   run: |
       #     curl -X POST -H 'Content-type: application/json' \
       #     --data '{"text": "❌ ECS deployment for cra-upd-dashboard (staging) failed to stabilize."}' \
       #     ${{ secrets.SLACK_NOTIFY_WEBHOOK }}
 
       - name: Report deployment to Sentinel
-        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && steps.ecs_wait.outcome == 'success'
+        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api') && steps.ecs_wait.outcome == 'success'
         uses: cds-snc/sentinel-forward-data-action@main
         with:
           input_data: '{"product": "cra-upd-dashboard", "version": "${{ github.sha }}", "repository": "${{ github.repository }}", "environment": "staging"}'
@@ -183,7 +224,7 @@ jobs:
           log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
 
       - name: Docker generate SBOM
-        if: github.repository == 'cds-snc/cra-arc-upd-tbpc'
+        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api')
         uses: cds-snc/security-tools/.github/actions/generate-sbom@34794baf2af592913bb5b51d8df4f8d0acc49b6f # v3.2.0
         env:
           TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
